version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: django_server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./ohto:/srv/django_server
          - ./log:/var/log/nginx
        depends_on:
          - django

    mysql_db:
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: ohto_db
        MYSQL_USER: ohto
        MYSQL_PASSWORD: Never123
        MYSQL_ROOT_PASSWORD: Never123
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./ohto/dbdata:/var/lib/mysql

    django:
        container_name: django
        build: ./ohto
        image: django_server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./ohto:/srv/django_server
          - ./log:/var/log/uwsgi
        depends_on:
          - mysql_db
