version: '3'
services:

    nginx:
        container_name: nginx1
        build: ./nginx
        image: docker/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./ohto:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django1
        build: ./ohto
        image: docker/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./ohto:/srv/docker-server
          - ./log:/var/log/uwsgi
